progress

diff --git a/0x00-hello_world/0-preprocessor b/0x00-hello_world/0-preprocessor
--- a/0x00-hello_world/0-preprocessor
+++ b/0x00-hello_world/0-preprocessor
@@ -1,2 +1,3 @@
 #!/bin/bash
+if [ -z "$CFILE" ]; then echo "Error: CFILE variable is not set."  exit 1 fi
 gcc -E "$CFILE" -o c
